export const getCardDescription = (name: string) => {
	return cards[name.toLowerCase()] ?? 'Unknown Card';
};

const cards: Record<string, string> = {
	social0: 'Giggling',
	social1: 'First Words',
	social2: 'Negotiating',
	social3: 'Commanding',
	mental0: 'Wondering',
	mental1: 'Discovering',
	mental2: 'Deducing',
	mental3: 'Innovating',
	physical0: 'Crawling',
	physical1: 'First Steps',
	physical2: 'Running',
	physical3: 'Leaping',
	introtrowel: 'Gardening Trowel',
	introbook: 'Animal Book',
	introdoll: 'Doll',
	introhat: "Eudicot's Old Hat",
	introtablet: 'Learning Tablet',
	introsportsball: 'Sportsball',
	perk_eyes: 'Eagle Eyes I',
	perk_extrafingers: 'Extra Fingers I',
	perk_spongybrain: 'Absorbent Brain I',
	perk_muscles: 'Super Strength I',
	perk_calm: 'Calm Temperament I',
	perk_eyes2: 'Eagle Eyes II',
	perk_extrafingers2: 'Extra Fingers II',
	perk_spongybrain2: 'Absorbent Brain II',
	perk_muscles2: 'Super Strength II',
	perk_calm2: 'Calm Temperament II',
	tradition: 'Tradition ',
	idealism: 'Idealism ',
	futurism: 'Futurism ',
	dreampeople: 'Dream People',
	engineeringbooks: 'Engineering Books',
	stresscry: 'Stress Cry',
	toughface: 'Tough Face',
	distraction: 'Distraction ',
	sunmedallion: 'Sun Medallion',
	sunmedallion2: 'Sun Medallion II',
	jacket: 'Cool Jacket',
	emojiproji: 'Emojiproji',
	cape: 'Superhero Cape',
	backpack: 'Memory Backpack',
	plascutter: 'Plascutter',
	tazegloves: 'Tazegloves',
	autohelm: 'Targeting Autohelm',
	dronerifle: 'Drone Rifle',
	virthelmet: 'Virtspace Helmet',
	braintrainer: 'Brain Trainer',
	holoeye: 'Holoeye Display',
	fidgetspinner: 'Vintage Focus Device',
	hopeye: 'Hopeye',
	hopeye2: 'Hopeye II',
	hopeye3: 'Hopeye III',
	vriki: 'Vriki',
	vriki2: 'Vriki II',
	vriki3: 'Vriki III',
	unisaur: 'Unisaur',
	unisaur2: 'Unisaur II',
	unisaur3: 'Unisaur III',
	vacubot: 'Pet Bot',
	alienweapon: 'Sonic Emitter',
	yellowflower: 'Yellow Flower',
	fruit: 'Bobberfruit',
	egg: 'Xeno Egg',
	wood: 'Mushwood Log',
	roots: 'Medicinal Roots',
	crystal: 'Crystal Cluster',
	device: 'Strange Device',
	cake: 'Cake',
	anemone1: "Anemone's Loyalty",
	anemone2: "Anemone's Loyalty II",
	anemone3: "Anemone's Loyalty III",
	cal1: "Cal's Strength",
	cal2: "Cal's Strength II",
	cal3: "Cal's Strength III",
	tang1: "Tangent's Focus",
	tang2: "Tangent's Focus II",
	tang3: "Tangent's Focus III",
	dys1: "Dys's Secret",
	dys2: "Dys's Secret II",
	dys3: "Dys's Secret III",
	marz1: "Marz's Ambition",
	marz2: "Marz's Ambition II",
	marz3: "Marz's Ambition III",
	tammy1: "Tammy's Care",
	tammy2: "Tammy's Care II",
	tammy3: "Tammy's Care III",
	rex1: "Rex's Hug",
	rex2: "Rex's Hug II",
	rex3: "Rex's Hug III",
	nomi1: "Nomi's Enthusiasm",
	nomi2: "Nomi's Enthusiasm II",
	nomi3: "Nomi's Enthusiasm III",
	vace1: "Vace's Confidence",
	vace2: "Vace's Confidence II",
	vace3: "Vace's Confidence III",
	sym1: "Sym's Curiosity",
	sym2: "Sym's Curiosity II",
	sym3: "Sym's Curiosity III",
	congruence: 'Congruence',
	dad: "Dad's Love",
	mom: "Mom's Love",
	tammygift: "Tammy's Homemade Gift",
	surpriseparty: 'Surprise Party',
	tangbang: 'Releasing Endorphins',
	'at ethem': 'I Ate Them All!',
	marzleader: 'Friend in High Places',
	vacestopfight: 'Breaking Up a Fight',
	overseer: 'Meeting the Overseer',
	vertumnaliaphysical: 'Bot-Athalon Champion',
	vertumnaliasocial: 'Talent Show Champion',
	vertumnaliamental: 'Science Fair Champion',
	vertumnaliaphysical2: 'Xeno Wrangling Champion',
	vertumnaliasocial2: 'Talent Show Champion II',
	vertumnaliamental2: 'Trivia Champion',
	vertumnaliabaking: 'Bake-off Champion',
	secondcommand: 'Second Administrator',
	secondgarrison: 'Second Security Officer',
	secondengineering: 'Second Engineer',
	secondgeoponics: 'Second Cultivator',
	secondquarters: 'Second Steward',
	secondexpeditions: 'Second Surveyor',
	pinkcandy: 'Pink Candy',
	tammysaved: 'Saving Tammy',
	hiding: 'Hiding in the Creche',
	bravery: 'Bravely Helping to Fight',
	eyebeast: 'Facing the Eyebeast',
	delusions: 'Delusions',
	hal: "Hal's Gratitude",
	tonin: "Uncle Tonin's Smile",
	tonindeath: 'Uncle Tonin and the Manticore',
	whiteflower: 'White Astrantia',
	toyxeno: 'Toy Xenofauna',
	photophonor: 'Photophonor',
	swallowedwhole: 'Swallowed Whole',
	anne: "Auntie Seedent's Love",
	defeatedfaceless: 'Defeated a Faceless',
	attack14: 'Destruction of the Strato',
	eudicot: 'Rescuing the Governor',
	databand: 'Gift From a Secret Admirer',
	daddeath: 'Saying Goodbye',
	sfcmembership: 'Secret Funtimes Club',
	sfcmembership2: 'Secret Funtimes Club II',
	sfcmystery: 'The Mystery of the Weird Smell',
	socks: "Cal's Pet Socks",
	socks2: "Cal's Pet Socks II",
	shimmercure: 'The Shimmer Cure',
	tangevidence: 'Engineered Plague',
	rankcadet: 'Cadet Rank',
	rankofficer: 'Officer Rank',
	ranklieutenant: 'Lieutenant Rank',
	echinacea: 'Babysitting for Echinacea',
	ultimate_shovel: 'Playing Shovelball With Cal',
	ultimate_farm: 'Harvesting the Fastest',
	ultimate_plants: 'Native Hybrid',
	ultimate_animals: 'Ending the Trippet Revolts',
	ultimate_babysitting: 'Hide and Seek With Nougat',
	ultimate_cooking: 'Snapbladder Surprise',
	ultimate_barista: 'The Mixologist',
	ultimate_photophonor: 'Coloring the World',
	ultimate_biology: 'Birthed a Floatcow',
	ultimate_physics: 'Fixing the Power Array',
	ultimate_writing: 'The Vertumna News Report',
	ultimate_tutoring: 'Tutoring for the Big Test',
	ultimate_nurse: 'Saving a Patient',
	ultimate_nursefail: 'Losing a Patient',
	ultimate_sportsball: 'Winning the Championship',
	ultimate_defense: 'The Ultimate Showdown',
	ultimate_lookout: 'Staying Awake on Guard Duty',
	ultimate_guard: 'Leading the East Wall Defense',
	ultimate_delivery: 'The Most Efficient Route',
	ultimate_depot: 'Organizing the Storage Room',
	ultimate_construction: 'Building the Tallest Tower',
	ultimate_assistant: "Earth's Fleet is Coming",
	ultimate_leader: 'Stopping the Earth Fleet',
	stuckmud: 'Up to Your Armpits in Mud',
	workmuscles: 'Working Those Muscles',
	robopower: 'Robo Power',
	hotsun: 'Under the Hot Hot Sun',
	cookingspices: 'The Spice Must Flow',
	ironstomach: 'Iron Stomach',
	stealfood: 'Stealing Food to Survive',
	starve: 'So... Hungry...',
	singing: 'Singing Your Heart Out',
	smart: 'Smart for My Age',
	pestcontrol: 'Pest Control',
	dizzyweed: 'Dizzy Weed',
	pullweed: 'Pulling Weeds',
	plantsspongecake: 'Cultivating Spongecake',
	radplant: 'Radioactive Plant',
	knowmushwood: 'Harvesting Mushwood',
	humantest: 'Testing on Humans',
	bleptea: 'A Potent Brew',
	violenttale: 'Telling a Violent Tale',
	gentletale: 'Telling a Gentle Tale',
	milksqueedger: 'Milking the Squeedger',
	friendhelp: 'Friends Helping Friends',
	animaltest: 'Testing on Animals',
	boring: 'Boooorriiiiing',
	scaryface: 'Putting on Your Scary Face',
	compromising: 'Compromising',
	askadult: 'Asking an Adult',
	debatable: "That's Debatable",
	comedown: 'Come Down, Nougat!',
	sabotage: 'Sabotaging',
	carnivore: 'Becoming a Carnivore',
	bully: 'Being a Bully',
	getcreative: 'Getting Creative',
	braidinghair: "Braiding Tammy's Hair",
	gossip: 'Dishing the Dirt',
	composer: 'Composing a Song',
	performing: 'Performing for an Audience',
	writing: 'Writing an Essay',
	dissection: 'Dissecting a Sugarbug',
	passtest: 'Acing a Test',
	failtest: 'Flunking a Test',
	embarrassinglesson: 'Embarrassing Lesson',
	holopalming: 'Hooked on Your Holopalm',
	goofoff: 'Goofing Off',
	fixing: 'Fixing Rundown Tech',
	smellyinside: 'Smells Worse Inside',
	geniusdeduction: 'Genius Deduction',
	stressfulmoment: 'A Stressful Event',
	sportsballplaying: 'Playing Sportsball',
	standup: 'Standing Up for Something',
	sharing: 'Sharing is Caring',
	buttkicked: 'Getting Your Butt Kicked',
	losttemper: 'Losing Your Temper',
	hurtingfriend: 'Hurting a Friend',
	workmuscles2: 'Working Those Muscles II',
	payingattention: 'Paying Attention',
	spying: 'Spying on a Friend',
	slaughterhordes: 'Slaughtering the Hordes',
	sharpshoot: 'Sharpshooting',
	fellinggiant: 'Felling a Giant',
	paperwork: 'Doing Paperwork',
	investigate: 'Investigation',
	makeout: 'Making Out',
	multitask: 'Multitasking',
	highestheight: 'Up to the Highest Height',
	plancomestogether: 'When a Plan Comes Together',
	learningpast: 'Learning About Earth',
	learningpast2: 'Learning About Earth II',
	vertumnagroup: 'The Vertumna Group',
	feast: 'A Grand Feast',
	caught: 'Getting Caught',
	camping: 'Camping Outside',
	gutfeeling: 'Gut Feeling',
	stranger: 'A Mysterious Stranger I',
	stranger2: 'A Mysterious Stranger II',
	stranger3: 'A Mysterious Stranger III',
	beautifulvista: 'A Beautiful Vista',
	counting: 'Hopeye Facts',
	bounceweasels: 'Raining Bounce Weasels',
	edible: 'Are Those Edible?',
	stayingcool: 'Staying Cool',
	snow: 'Playing in the Snow',
	enormous: "That's One Big... Something",
	bushbubdance: "The Bushbub's Dance",
	lost: 'Getting Lost in the Fog',
	floatcow: 'Lassoing a Floatcow',
	helpanimal: 'Helping an Animal',
	shimmerglade: 'Escaping the Shimmer Glade',
	weird: 'That Was Weird',
	headache: 'Ow My head',
	thumper: 'Thud of the Thumper',
	tracking: 'Tracking the Airsquid',
	noctilucent: "Noctilucent's Disdain",
	unisaurhorn: "A Unisaur's Horn",
	leftfordead: 'Crushed by a Faceless',
	payload: 'Priming the Payload',
	beautiful: "It's All Too Beautiful",
	wormhole: 'Timey Wimey Wormhole Stuff',
};
