import { PerkDetails } from '../types/interface/perkDetails';

export const getPerkDetails = (name: string) => {
	return perksById.get(name.toLowerCase()) ?? null;
};

const perks: PerkDetails[] = [
	{
		id: 'eyes',
		name: 'Eagle Eyes',
		type: 'enhancement',
		abilityId: 'perkPerceptionAnimals',
		value: '1',
		suit: '',
		description: 'Increase Perception and Animals faster',
		snippet1: 'your birdlike eyes miss nothing.',
		snippet2: 'could spot a dorbsmoth from a klick away.',
		snippet3: 'You could spot a dorbsmoth from a klick away.',
	},
	{
		id: 'extraFingers',
		name: 'Extra Fingers',
		type: 'enhancement',
		abilityId: 'perkCreativityOrganization',
		value: '1',
		suit: '',
		description: 'Increase Creativity and Organization faster',
		snippet1: 'your extra fingers come in handy (get it? handy).',
		snippet2: 'are a polydactyl, like many great photophonor players.',
		snippet3: "You're a polydactyl, like many great photophonor players.",
	},
	{
		id: 'spongyBrain',
		name: 'Absorbent Brain',
		type: 'enhancement',
		abilityId: 'perkBiologyEngineering',
		value: '1',
		suit: '',
		description: 'Increase Biology and Engineering faster',
		snippet1: 'a keen learner thanks to the hyperactive neurons in your brain.',
		snippet2: 'a fast learner.',
		snippet3: "You're a keen learner thanks to the hyperactive neurons in your brain.",
	},
	{
		id: 'muscles',
		name: 'Super Strength',
		type: 'enhancement',
		abilityId: 'perkToughnessCombat',
		value: '1',
		suit: '',
		description: 'Increase Toughness and Combat faster',
		snippet1: 'still the strongest kid in your class.',
		snippet2: "build muscle mass like nobody's business.",
		snippet3: "You build muscle mass like nobody's business.",
	},
	{
		id: 'calm',
		name: 'Calm Temperament',
		type: 'enhancement',
		abilityId: 'gearReduceStress',
		value: '2',
		suit: '',
		description: '2 less Stress when you gain Stress',
		snippet1: 'just the chillest, most easy-going person.',
		snippet2: 'stay calm when others get frazzled.',
		snippet3: 'You stay calm when others get frazzled.',
	},
	{
		id: 'nothing',
		name: 'No Enhancement',
		type: 'enhancement',
		abilityId: 'extraKudos',
		value: '2',
		suit: '',
		description: '2 bonus Kudos when you gain Kudos',
		snippet1: 'doing just fine with no genetic augmentation, thanks.',
		snippet2: 'are special in your own way.',
		snippet3: '',
	},
	{
		id: 'gearSlot',
		name: 'Extra Gear Slot',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Equip an additional Gear',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'petUpgrades1',
		name: 'Level II Pets',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Upgrade pet cards via Relaxing in the Park',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'petUpgrades2',
		name: 'Level III Pets',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Upgrade pet cards via Relaxing in the Park',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'shopClothes',
		name: 'Shop Clothes',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'New cards in the depot',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'shopGadgets',
		name: 'Shop Gadgets',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'New cards in the depot',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'extraDraw',
		name: 'Extra Card Draw',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Draw an extra card at the start of challenge (effect stacks)',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'collectiblesHighlight',
		name: 'Highlight Collectibles',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'All collectibles glow',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'collectiblesMore',
		name: 'More Collectibles',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Collectibles respawn faster and more slots are filled',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'jobAnalyzePlants',
		name: 'Native Botany',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Unlock Xenobotany Research in Geoponics',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'shopWeapons',
		name: 'Shop Weapons',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'New cards in the depot',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'spa',
		name: 'Spa',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Pay to remove cards in the quarters spa',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'training',
		name: 'Card Training',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Update basic cards in the garrison gym',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'extraStartingPerk',
		name: 'Extra Enhancement',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Enhance your DNA in Engineering',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'boostSocial',
		name: 'Social Boost',
		type: 'skill',
		abilityId: 'plusSkill',
		value: '1',
		suit: 'social',

		description: '+1 to Social Increases',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'boostMental',
		name: 'Mental Boost',
		type: 'skill',
		abilityId: 'plusSkill',
		value: '1',
		suit: 'mental',

		description: '+1 to Mental Increases',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'boostPhysical',
		name: 'Physical Boost',
		type: 'skill',
		abilityId: 'plusSkill',
		value: '1',
		suit: 'physical',

		description: '+1 to Physical Increases',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'skillsBoost',
		name: 'Small Skills Boost',
		type: 'skill',
		abilityId: 'plusSkillChance',
		value: '5',
		suit: '',
		description: '5% Chance to gain 1 extra skill',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'relaxBetter',
		name: 'Improved Relaxing',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Choose from 3 cards when relaxing',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'giftBetter',
		name: 'Improved Gifting',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Give gifts every month instead of once a season',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'extraKudos',
		name: 'Extra Kudos',
		type: 'skill',
		abilityId: 'extraKudos',
		value: '1',
		suit: '',
		description: '+ 1 Kudos every time you receive kudos',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'loveDestress',
		name: 'Friendship Decreases Stress',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: '- 1 Stress any time you gain Friendship',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'noBottlenecks',
		name: 'Avoid Blocking Events',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Slip past all path-blocking\\nexplore events',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'skipNewCard',
		name: 'Optional Card Skip',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Can choose not to take new cards',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'injuryImmune',
		name: 'Immune to Injury',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Never receive the Injury status effect when hurt',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'socialPlusOne',
		name: '+1 to Social cards',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Yellow cards get +1 in social challenges',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'mentalPlusOne',
		name: '+1 to Mental cards',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Blue cards get +1 in mental challenges',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'physicalPlusOne',
		name: '+1 to Physical cards',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Red cards get +1 in physical challenges',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'reduceExploreStress',
		name: 'Reduce Exploration Stress',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Every event in exploring causes +10 stress instead of +15',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: '???',
		name: 'Know the best Job Challenge Score',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description:
			'Best possible job challenge score using cards in hand is displayed next to goal',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'autoplayFairy',
		name: 'Autoplay Fairy',
		type: 'skill',
		abilityId: '',
		value: '',
		suit: '',
		description: 'Autoplay Fairy sometimes plays the best hand for you',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_stressed',
		name: 'Stressed Out',
		type: 'status',
		abilityId: '',
		value: '',
		suit: '',
		description: "Can't do anything but relax.",
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_calm',
		name: 'Clear Minded',
		type: 'status',
		abilityId: 'plusSkillChance',
		value: '10',
		suit: '',
		description: '10% chance to get a bonus +1 when increasing skills.',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_enlightened',
		name: 'Enlightened',
		type: 'status',
		abilityId: 'plusSkill',
		value: '1',
		suit: 'mental',
		description: '+1 to all Mental skill increases for 3 months.',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_love',
		name: 'Smitten',
		type: 'status',
		abilityId: 'plusSkill',
		value: '1',
		suit: 'social',
		description: '+1 to all Social skill increases for 3 months.',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_mourning',
		name: 'In Mourning',
		type: 'status',
		abilityId: 'plusSkill',
		value: '-1',
		suit: '',
		description: 'All skill increases reduced by -1 for 3 months.',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_starving',
		name: 'Starving',
		type: 'status',
		abilityId: 'plusSkill',
		value: '-1',
		suit: 'physical',
		description: 'Physical skill increases reduced by -1',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_injured',
		name: 'Injured',
		type: 'status',
		abilityId: 'plusSkill',
		value: '-1',
		suit: 'physical',
		description: 'Physical skill increases reduced by -1, heal by relaxing.',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_hormones',
		name: 'Hormones',
		type: 'status',
		abilityId: 'multiplyRebellion',
		value: '200',
		suit: '',
		description: 'Rebellion increases tripled.',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_insomnia',
		name: 'Insomnia',
		type: 'status',
		abilityId: 'plusSkill',
		value: '-1',
		suit: 'mental',
		description: 'Mental skill increases reduced by -1 for 3 months.',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_grounded',
		name: 'Grounded',
		type: 'status',
		abilityId: 'multiplyRebellion',
		value: '-100',
		suit: '',
		description: "Can't explore. Loyalty increases doubled.",
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_popular',
		name: 'Popular',
		type: 'status',
		abilityId: 'multiplyKudos',
		value: '100',
		suit: '',
		description: 'Kudos doubled for 3 months.',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_heroic',
		name: 'Heroic',
		type: 'status',
		abilityId: 'plusSkill',
		value: '1',
		suit: 'physical',
		description: '+1 to all Physical skill increases for 3 months.',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
	{
		id: 'status_feud',
		name: 'Feud',
		type: 'status',
		abilityId: 'plusSkill',
		value: '-1',
		suit: 'social',
		description: 'Social skill increases reduced by -1 for 3 months.',
		snippet1: '',
		snippet2: '',
		snippet3: '',
	},
];

const perksById = new Map(perks.map((perk) => [perk.id.toLowerCase(), perk]));
