import { SkillDetails } from '../types/interface/skillDetails';

export const getSkillDetails = (name: string) => {
	return skillsById.get(name.toLowerCase()) ?? null;
};

const skills: SkillDetails[] = [
	{
		id: 'empathy',
		name: 'Empathy',
		location: 'Creche',
		cardSuit: 'social',
		perk30: 'spa',
		perk60: 'relaxBetter',
		perk100: 'loveDestress',
		notes: 'Understanding other people',
	},
	{
		id: 'persuasion',
		name: 'Persuasion',
		location: 'Command',
		cardSuit: 'social',
		perk30: 'socialPlusOne',
		perk60: 'extraKudos',
		perk100: 'boostSocial',
		notes: 'Charisma to command people and speak in public',
	},
	{
		id: 'creativity',
		name: 'Creativity',
		location: 'Creche',
		cardSuit: 'social',
		perk30: 'shopClothes',
		perk60: 'skillsBoost',
		perk100: 'giftBetter',
		notes: 'Artistic ability and capacity for novel ideas',
	},
	{
		id: 'bravery',
		name: 'Bravery',
		location: 'Command',
		cardSuit: 'social',
		perk30: 'extraDraw',
		perk60: 'reduceExploreStress',
		perk100: 'extraDraw',
		notes: 'For both social and dangerous situations',
	},
	{
		id: 'reasoning',
		name: 'Reasoning',
		location: 'Engineering',
		cardSuit: 'mental',
		perk30: 'mentalPlusOne',
		perk60: 'autoplayFairy',
		perk100: 'boostMental',
		notes: 'Problem solving and general knowledge',
	},
	{
		id: 'organization',
		name: 'Organizing',
		location: 'Creche',
		cardSuit: 'mental',
		perk30: 'gearSlot',
		perk60: 'extraDraw',
		perk100: 'skipNewCard',
		notes: 'Dedication to neatness, management',
	},
	{
		id: 'engineering',
		name: 'Engineering',
		location: 'Engineering ',
		cardSuit: 'mental',
		perk30: 'extraDraw',
		perk60: 'shopGadgets',
		perk100: 'gearSlot',
		notes: 'Study of machines, physics, math, and programming',
	},
	{
		id: 'biology',
		name: 'Biology',
		location: 'Geoponics',
		cardSuit: 'mental',
		perk30: 'jobAnalyzePlants',
		perk60: 'collectiblesMore',
		perk100: 'extraStartingPerk',
		notes: 'Study of plants, chemistry, and the human body',
	},
	{
		id: 'toughness',
		name: 'Toughness',
		location: 'Garrison',
		cardSuit: 'physical',
		perk30: 'physicalPlusOne',
		perk60: 'training',
		perk100: 'injuryImmune',
		notes: 'Physical strength and stamina',
	},
	{
		id: 'perception',
		name: 'Perception',
		location: 'Expeditions',
		cardSuit: 'physical',
		perk30: 'collectiblesHighlight',
		perk60: 'collectiblesMore',
		perk100: 'noBottlenecks',
		notes: 'Ability to find things and sneak past things',
	},
	{
		id: 'combat',
		name: 'Combat',
		location: 'Garrison',
		cardSuit: 'physical',
		perk30: 'shopWeapons',
		perk60: 'extraDraw',
		perk100: 'boostPhysical',
		notes: 'Tactics and weapons',
	},
	{
		id: 'animals',
		name: 'Animals',
		location: 'Expeditions',
		cardSuit: 'physical',
		perk30: 'petUpgrades1',
		perk60: 'gearSlot',
		perk100: 'petUpgrades2',
		notes: 'Familiarity with xenofauna, hunting, ranching',
	},
	{
		id: 'kudos',
		name: 'Kudos',
		location: '',
		cardSuit: 'none',
		perk30: '',
		perk60: '',
		perk100: '',
		notes: 'Reputation-based currency',
	},
	{
		id: 'stress',
		name: 'Stress',
		location: '',
		cardSuit: 'none',
		perk30: '',
		perk60: '',
		perk100: '',
		notes: 'Physical and mental exhaustion',
	},
	{
		id: 'rebellion',
		name: 'Rebellion',
		location: '',
		cardSuit: 'none',
		perk30: '',
		perk60: '',
		perk100: '',
		notes: 'Relationship with adults and colony government',
	},
];

const skillsById = new Map(skills.map((skill) => [skill.id.toLowerCase(), skill]));
